// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhkMoUXa6y2_oiNUQTziXsE801AJKakaM',
    appId: '1:843815321202:web:5cba49479c44b7fd078ceb',
    messagingSenderId: '843815321202',
    projectId: 'tapnroute-945f8',
    authDomain: 'tapnroute-945f8.firebaseapp.com',
    storageBucket: 'tapnroute-945f8.appspot.com',
    measurementId: 'G-N4DGH49J3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD6sIXuei31huq3HTbke_s35zPyjMb154',
    appId: '1:843815321202:android:ff75bf62bfb93f67078ceb',
    messagingSenderId: '843815321202',
    projectId: 'tapnroute-945f8',
    storageBucket: 'tapnroute-945f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzxPNtWtfWxwidI_hHP7cMH1YDSZTwwq4',
    appId: '1:843815321202:ios:a3adcbad800cd13d078ceb',
    messagingSenderId: '843815321202',
    projectId: 'tapnroute-945f8',
    storageBucket: 'tapnroute-945f8.appspot.com',
    androidClientId: '843815321202-4vnaut7iol6uckmlt4rtr23d939i1j7r.apps.googleusercontent.com',
    iosClientId: '843815321202-tfiq19h7qtee82sjmdqptetqndb4h08k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapnroute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzxPNtWtfWxwidI_hHP7cMH1YDSZTwwq4',
    appId: '1:843815321202:ios:a3adcbad800cd13d078ceb',
    messagingSenderId: '843815321202',
    projectId: 'tapnroute-945f8',
    storageBucket: 'tapnroute-945f8.appspot.com',
    androidClientId: '843815321202-4vnaut7iol6uckmlt4rtr23d939i1j7r.apps.googleusercontent.com',
    iosClientId: '843815321202-tfiq19h7qtee82sjmdqptetqndb4h08k.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapnroute',
  );
}
